# Variables and Basic Data Structures

## Introducing `numpy` Arrays

In [1]:
import numpy as np

In [2]:
x = np.array([1, 4, 3])

In [3]:
x

array([1, 4, 3])

In [4]:
y = np.array([
    [1,4,3],
    [9,2,7]
])

In [5]:
y

array([[1, 4, 3],
       [9, 2, 7]])

In [6]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [3, 4],
    [5, 6]
])

In [7]:
a * b

array([[ 3,  8],
       [15, 24]])

In [8]:
a.dot(b)

array([[13, 16],
       [29, 36]])

In [9]:
a**b

array([[   1,   16],
       [ 243, 4096]])

In [10]:
a.T

array([[1, 3],
       [2, 4]])