# Functions

## Problems

2. Write a function `my_checker_board(n)` where the output `n` is an $n \times n$ array with the following form:

$$
m = 
\begin{matrix}
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1
\end{matrix}
$$

Note that the upper-left element should always be 1. Assume that n is a strictly positive integer.

In [17]:
import numpy as np
def my_checker_board(n):
    if n == 1:
        return n
    board = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                board[i][j] = 1
    return board

In [18]:
my_checker_board(1)

1

In [19]:
my_checker_board(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
my_checker_board(3)

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [21]:
my_checker_board(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

4. Write a function `my_split_matrix(m)`, where m is an array, the output is a list $\left[m_1, m_2\right]$ where $m_1$ is the left half of m, and $m_2$ is the right half of m. In the case where there is an odd number of columns, the middle column should go to $m_1$. Assume that m has at least two columns.

In [45]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
m[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8],
       [4, 5],
       [7, 8]])

In [71]:
def my_split_matrix(m):
    if len(m[0]) % 2 == 0:
        n = len(m[0]) // 2
    else:
        n = 1 + len(m[0]) // 2
    m1, m2 = m[:, :n], m[:, n:]
    def reorg_mattrix(m):
        if len(m[0]) == 1:
            return np.array([_[0] for _ in m])
        return m
    return [reorg_mattrix(m1), reorg_mattrix(m2)]

In [72]:
my_split_matrix(m)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([3, 6, 9])]

In [66]:
len(m2)

3

In [68]:
for i in m2:
    print(i)

[3]
[6]
[9]
